repos:
 - url: "https://dev.azure.com/schwarzit/schwarzit.stackit-mongodb/_git/stackit-postgres-zalando-postgres-operator"
   folders:
    - "folder 1"
    - "folder 2"
    - "folder 3"
    - "folder 4"
 - url: "https://dev.azure.com/schwarzit/schwarzit.stackit-mongodb/_git/stackit-postgres-zalando-postgres-operator"
   folders:
    - "folder 1"
 - url: "https://dev.azure.com/schwarzit/schwarzit.stackit-mongodb/_git/stackit-postgres-zalando-postgres-operator"
   folders:
    - "folder 1"

